version: '3.5'
services:
  backend:
    build:
      context: ../backend
      args:
        username: "nonroot"
    ports:
     - "5000:5000"
    depends_on:
      - db
      - db_test
    volumes:
      - ../backend:/server
    networks:
      - dishes
    command: pipenv run flask run --host=0.0.0.0
  frontend:
    build:
      context: ../frontend
    ports:
      - "4200:4200"
      - '9876:9876'
    volumes:
      - ../frontend:/frontend
    networks:
      - dishes
    command: ng serve --host 0.0.0.0 --port 4200 --poll=2000
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'dishes_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_super_password'
    ports:
      - '3306:3306'
    volumes:
      - dishes_db:/var/lib/mysql
    networks:
      - dishes
  db_test:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'dishes_db_test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_super_password'
    ports:
      - '3307:3306'
    volumes:
      - dishes_db_test:/var/lib/mysql
    networks:
      - dishes
    
    
networks:
  dishes:
    name: dishes
    driver: bridge
    ipam:
      driver: default

volumes:
  dishes_db:
  dishes_db_test:
